# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0411f740d0985e68416f3172d866cf35ee8129f858cff9661d1451977337b5bbb479dfc2102e336ee79098150266ebbc2105aa468948363051ac7cd9626f85a5

test:
  secret_key_base: 19ecd5f3d9e0c5f408cf8ab84587376307e7708d3bdeae3c1c3f4df72e0bf4ad4667deddabaab3efc0a95bbbec449224074364b6b1b9b399e666f94920c3191f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
